// File generated by Blink v0.18.0 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void;
export declare namespace DataToServer {
	type Player = Player;
	export const ButtonClicked: {
		fire: (Value: Player) => void;
	};
	export const Rebirth: {
		fire: (Value: Player) => void;
	};
}
