// File generated by Blink v0.18.6 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void;
export declare namespace DataToServer {
	type Player = Player;
	export const ButtonClicked: {
		on: (Listener: (Player: Player, Value: Player) => void) => () => void;
	};
	export const Rebirth: {
		on: (Listener: (Player: Player, Value: Player) => void) => () => void;
	};
}
